export const api = {
  baseUrl: "https://bookzone.onrender.com",
  registerApi: "/api/sign-up",
  loginApi: "/api/login",
  usersApi: "/api/users",
  shelfApi: "/api/users/shelf",
  authorsApi: "/api/authors",
  booksApi: "/api/books",
  myBooksApi: "/api/books/my-books",
  authorBooksApi: "/api/books/my-books",
  searchBooksApi: "/api/books/my-books",
  booksCommentApi: "/api/books/comment",
  filesApi: "/api/files",
  base64FilesApi: "/api/files/base64",
  deleteFilesApi: "/api/files/delete",
};
